#!/usr/bin/env python3
# Title: donkey
# Description: Removes the tail from a file
# Author: Andrew T. Withers (atw31337@gmail.com)

import sys, getopt
from shutil import move
from random import randint

def usage():
	print('Usage: '+sys.argv[0]+' -n <NUM> [OPTION]... <INPUT FILE> ')
	print()
	print('	 -o <FILE>      Output file')
	print('	 -n <NUM>	Output all lines except the last n number of lines')
	print('	 -e	  	Edit input file. Overwrites the original file. Cannot be used with -o')
	print()

def file_length(fname):
	try:
		f = open(fname)
		with f:
			for i, l in enumerate(f):
				pass
		return i + 1
	except:
		print("Error reading file: ", fname)
		sys.exit(1)

def main():
	edit = 'false'
	newfile = 'false'
	try:
		opts, args = getopt.getopt(sys.argv[1:], 'ho:n:e', ['help'])	# Get parameters from command line
	except getopt.GetoptError as err:
		print(str(err))
		usage()
		sys.exit(2)
	for o, a in opts:	# Process options
		if o == "-o":
			output = a
			newfile = 'true'
		elif o == "-n":
			remove = a
		elif o == "-e":
			output = "/tmp/" + str(randint(100000,900000))
			edit = 'true'
		elif o in ("-h", "--help"):
			usage()
			sys.exit(0)
		else:
			assert False, "unhandled option"

	if newfile == 'true' and edit == 'true':
		print("option -e cannot be used in combination with option -o")
		usage()
		sys.exit(1)

	try:
		input = args[0]
	except:
		print("The input file is not defined")
		usage()
		sys.exit(1)

	try:
		remove
	except NameError:
		print("-n is a required option")
		usage()
		sys.exit(1)

	totalLines = file_length(input)		# Total number of lines in the original file
	diffLines = totalLines - int(remove)	# Number of lines in the output
	try:
		output
	except NameError:       # Output file has not been specified
		output = "stdout"

	count=1
	try:
		iFile = open(input)	# Open the input file
	except:
		print("Error reading file: ", input)
		sys.exit(1)
	with iFile:
		if output != "stdout":
			oFile = open(output, "w+")	# Open the output file
		for l in iFile:
			if count <= diffLines:
				if output == "stdout":		# Write to stdout
					sys.stdout.write(l)
					sys.stdout.flush()
				else:
					oFile.write(l)		# Write to output file
				count+=1
			else:
				break		# Stop reading from input once the output limit is reach

	if output != "stdout":
		oFile.close()
		if edit == 'true':
			move(output, input)

if __name__ == "__main__":
	main()
